name: "Build and Test"
on: [push]

#
# For each push, check that the project builds and tests pass.
#

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install

    # Version changing should not cause any changes to files.

    - run: npm run version
    - name: Check Changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: Ensure Unchanged
      if: steps.changes.outputs.changed == 1
      run: echo "Version was not incremented. Run [npm version] locally before PRing."; exit 1;

    # Running build may be platform-specific.

    - run: npm build
    - run: npm run lint
    - run: npm run test
