name: "Branch on Issue"
on:
  issues:
    types: [assigned]

# Create a new branch for every single assigned issue.

jobs:
  issue-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pull-request:
    runs-on: ubuntu-latest
    needs: issue-branch
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
