name: "Release"
on:
  push:
    tags:
      - "v*"

# Release and update the Ghost app live.

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install

    # Ensure the correct version in the package file.

    - run: npm run ver
    - run: npm run zip
    - name: Deploy Ghost Theme
      uses: TryGhost/action-deploy-theme@v1.4.1
      with:
        api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
        api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
        file: dist/dopamine.zip
    - name: Deploy Notification
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: success
        details: Deployed to Ghost successfully!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
